using System.Diagnostics.CodeAnalysis;

namespace ConsoleApp1.Services
{
    /// <summary>
    /// Contains a mapping of column names to column indexes for the customer import CSV file.
    /// </summary>
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public enum ColumnIndexMap
    {
        AccountNumber = 0,
        MasterCustomerDetailsFlag = 1,
        PrimaryAccountHolderFlag = 2,
        Title = 3,
        FirstName = 4,
        MiddleInitial = 5,
        LastName = 6,
        NameSuffix = 7,
        BusinessName = 8,
        StreetAddress1 = 9,
        StreetAddress2 = 10,
        StreetAddress3 = 11,
        City = 12,
        State = 13,
        ZipCodePre = 14,
        ZipCodeSuffix = 15,
        DateOfBirth = 16,
        DeathDate = 17,
        PhoneNumber = 18,
        EmailAddress = 19,
        SSN = 20,
        CommunicationPreference = 21,
        Income = 22,
        EmployerName = 23,
        EmploymentDate = 24,
        MemberStartDate = 25,
        RelationshipCode = 26,
        RaddonSegment = 27,
        County = 28,
        Region = 29,
        Branch = 30,
        CheckingFlag = 31,
        CDFlag = 32,
        MoneyMarketFlag = 33,
        AutoLoanFlag = 34,
        CreditCardFlag = 35,
        PLFlag = 36,
        HELOCFlag = 37,
        HomeEquityLoanFlag = 38,
        FirstMortgageFlag = 39,
        StudentLoanFlag = 40,
        OnlineBankingFlag = 41,
        BillPayFlag = 42,
        DebitCardFlag = 43,
        NegShareWarning = 44,
        BankruptcyWarning = 45,
        DQWarning = 46,
        BadAddressWarning = 47,
        BadEmailWarning = 48,
        ExcessiveFeesWarning = 49,
        CreditScore1 = 50,
        CreditScoreDate1 = 51,
        CreditScore2 = 52,
        CreditScoreDate2 = 53,
        CreditScore3 = 54,
        CreditScoreDate3 = 55,
        CreditScore4 = 56,
        CreditScoreDate4 = 57,
        ProductAccountNumber = 58,
        ProductType = 59,
        Description = 60,
        MonthlyPayment = 61,
        DateOpened = 62,
        Rate = 63,
        TermType = 64,
        TermInMonths = 65,
        OriginalBalance = 66,
        CurrentBalance = 67,
        CCLimit = 68,
        FlexFlag1 = 69,
        FlexFlag2 = 70,
        FlexFlag3 = 71,
        FlexFlag4 = 72,
        FlexFlag5 = 73,
        FlexFlag6 = 74,
        FlexFlag7 = 75,
        FlexFlag8 = 76,
        FlexFlag9 = 77,
        FlexFlag10 = 78,
        FlexChar1 = 79,
        FlexChar2 = 80,
        FlexChar3 = 81,
        FlexChar4 = 82,
        FlexNum1 = 83,
        FlexNum2 = 84,
        FlexNum3 = 85,
        FlexNum4 = 86,
        FlexDate1 = 87,
        FlexDate2 = 88,
        FlexDate3 = 89,
        FlexDate4 = 90,
        FlexMoney1 = 91,
        FlexMoney2 = 92,
        FlexMoney3 = 93,
        FlexMoney4 = 94,
        FlexRate1 = 95,
        FlexRate2 = 96,
        FlexRate3 = 97,
        FlexRate4 = 98
    }
}